# Generated by Django 4.1.5 on 2023-01-11 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coach', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lessons.hall')),
                ('members', models.ManyToManyField(related_name='lessons', to='lessons.member')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
            },
        ),
    ]
